### ISSUE TITLE
Check that over-consumption isn't taking place

### ISSUE THREAD

**Issue by noobanidus** [noobanidus/Whoops#2]

**Comment by NielsPilgaard** [comment]
I've received numerous reports that 2 blocks are consumed per click, I have yet to test it myself though.

**Comment by noobanidus** [comment]
This should be resolved in the latest two releases of 1.14.4/1.15.2.

**Comment by NielsPilgaard** [comment]
Thank you kindly :)

**Comment by noobanidus** [comment]
Please don't hesitate to open another issue if it crops up again. I had thought it was one thing but it turned out to be something else entirely (turns out that I was shrinking the stack when the "try to place this item" was already doing that).
